name: Analyze Articles

on:
  schedule:
    - cron: '0 */6 * * *'  # Run every 6 hours
  workflow_dispatch:  # Allow manual triggering

jobs:
  analyze:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run article analysis
      env:
        READWISE_TOKEN: ${{ secrets.READWISE_TOKEN }}
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
        MONGODB_DATABASE: ${{ secrets.MONGODB_DATABASE }}
        MONGODB_LATER_COLLECTION: ${{ secrets.MONGODB_LATER_COLLECTION }}
        ANALYSIS_BATCH_SIZE: '100'  # Process 100 articles per run
      run: |
        python analyze_articles.py 