name: Daily Readwise Fetch

on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: '0 0 * * *'
  # Allow manual trigger
  workflow_dispatch:

jobs:
  fetch-readwise:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create .env file
      run: |
        echo "READWISE_TOKEN=${{ secrets.READWISE_TOKEN }}" > .env
        echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> .env
        echo "MONGODB_DATABASE=${{ secrets.MONGODB_DATABASE }}" >> .env
        echo "MONGODB_LATER_COLLECTION=${{ secrets.MONGODB_LATER_COLLECTION }}" >> .env
        echo "MONGODB_ARCHIVE_COLLECTION=${{ secrets.MONGODB_ARCHIVE_COLLECTION }}" >> .env

    - name: Run fetch script
      run: python main.py 