name: Daily Readwise HTML Fetch

on:
  schedule:
    # Runs at 01:00 UTC every day (1 hour after the metadata sync)
    - cron: '0 1 * * *'
  # Allow manual trigger
  workflow_dispatch:

jobs:
  fetch-readwise-html:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create .env file
      run: |
        echo "READWISE_TOKEN=${{ secrets.READWISE_TOKEN }}" > .env
        echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> .env
        echo "MONGODB_DATABASE=${{ secrets.MONGODB_DATABASE }}" >> .env
        echo "MONGODB_LATER_COLLECTION=${{ secrets.MONGODB_LATER_COLLECTION }}" >> .env
        echo "MONGODB_ARCHIVE_COLLECTION=${{ secrets.MONGODB_ARCHIVE_COLLECTION }}" >> .env
        echo "MONGODB_LATER_HTML_COLLECTION=${{ secrets.MONGODB_LATER_HTML_COLLECTION }}" >> .env
        echo "MAX_HTML_DOCUMENTS=${{ secrets.MAX_HTML_DOCUMENTS || '6000' }}" >> .env

    - name: Run HTML fetch script
      run: python html_fetch.py 